version: '3'
volumes:
  postgis-data:

services:
  lizmap:
    image: 3liz/lizmap-web-client:${LIZMAP_VERSION_TAG}
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_USER_ID}
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_CONFIG_INCLUDE: /srv/etc
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGPASSFILE: /srv/etc/pgpass.conf
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - ${LIZMAP_DIR}/var/lizmap-db:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - ${LIZMAP_DIR}/www/var/log:/www/lizmap/var/log
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/var/lizmap-modules:/www/lizmap/lizmap-modules
      - ${LIZMAP_DIR}/var/lizmap-my-packages:/www/lizmap/my-packages
    command:
      - php-fpm
    restart: unless-stopped
  map:
    image: 3liz/qgis-map-server:${QGIS_VERSION_TAG}
    environment:
      QGSRV_CACHE_SIZE: '20'
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_USER: ${LIZMAP_USER_ID}:${LIZMAP_USER_GID}
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_SERVER_WORKERS: ${QGIS_MAP_WORKERS}
      QGSRV_SERVER_PLUGINPATH: /srv/plugins
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGSPASSFILE: /srv/etc/pgpass.conf
      QGIS_OPTIONS_PATH: /srv/etc/qgis
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/wps-data:/srv/data
    ports:
      - ${OWS_PORT}:8080
    restart: unless-stopped
  redis:
    image: redis:5-alpine
  web:
    image: nginx:1
    user: ${LIZMAP_USER_ID}:${LIZMAP_USER_ID}
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${LIZMAP_DIR}/var/log/nginx:/var/log/nginx
      - ${LIZMAP_DIR}/var/nginx-cache:/var/cache/nginx
      - ${LIZMAP_DIR}:/srv/lizmap
    ports:
      - ${LIZMAP_PORT}:8080
    depends_on:
      - lizmap
  db:
    # https://github.com/kartoza/docker-postgis
    image: kartoza/postgis:13-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
  cloud: 
    # https://cloudcmd.io
    ports:
      - ${CLOUDCMD_PORT}:8000
    environment:
      - CLOUDCMD_AUTH=true
      - CLOUDCMD_USERNAME=${CLOUDCMD_USERNAME}
      - CLOUDCMD_PASSWORD=${CLOUDCMD_PASSWORD}
      - CLOUDCMD_ROOT=/lizmap
    volumes:
      # - ~:/root
      - ${LIZMAP_DIR}/instances:/lizmap
    image: coderaiser/cloudcmd
    restart: unless-stopped
